#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Jun 06, 2020 10:34:15 AM IST  platform: Linux
set vTcl(timestamp) ""


set image_list { \
    icons8_train_100_png ./Documents/Tkinter/img/icons8-train-100.png \
}
   vTcl:create_project_images $image_list   ;# In image.tcl


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 600x450+340+170
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Admin"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab43 \
        -background #5e5e5e \
        -font {-family {Noto Serif} -size 21 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -text {Railway Reservation System} 
    vTcl:DefineAlias "$top.lab43" "Label1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra44 \
        -borderwidth 10 -relief groove -background $vTcl(actual_gui_bg) \
        -height 255 -width 515 
    vTcl:DefineAlias "$top.fra44" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra44
    label $site_3_0.lab49 \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -text {Train_name :} 
    vTcl:DefineAlias "$site_3_0.lab49" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab50 \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -text {Train_no :} 
    vTcl:DefineAlias "$site_3_0.lab50" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -text {From :} 
    vTcl:DefineAlias "$site_3_0.lab51" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab52 \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 11 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -text {To :} 
    vTcl:DefineAlias "$site_3_0.lab52" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab53 \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 10 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -text {Departure_time :} 
    vTcl:DefineAlias "$site_3_0.lab53" "Label6" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent54 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent54" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent55 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent55" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent56 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent56" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent57 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent57" "Entry4" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent58 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent58" "Entry5" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab49 \
        -in $site_3_0 -x 10 -y 40 -width 130 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 10 -y 80 -width 119 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 10 -y 120 -width 107 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 10 -y 160 -width 109 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 10 -y 200 -width 135 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent54 \
        -in $site_3_0 -x 150 -y 40 -width 306 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent55 \
        -in $site_3_0 -x 150 -y 80 -width 306 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent56 \
        -in $site_3_0 -x 150 -y 120 -width 306 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent57 \
        -in $site_3_0 -x 150 -y 160 -width 306 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent58 \
        -in $site_3_0 -x 150 -y 200 -width 306 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    button $top.but45 \
        -background $vTcl(actual_gui_bg) -borderwidth 6 \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Add 
    vTcl:DefineAlias "$top.but45" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but46 \
        -background $vTcl(actual_gui_bg) -borderwidth 6 \
        -font {-family {DejaVu Sans} -size 10 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Modify 
    vTcl:DefineAlias "$top.but46" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but47 \
        -background $vTcl(actual_gui_bg) -borderwidth 6 \
        -font {-family {DejaVu Sans} -size 10 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Clear 
    vTcl:DefineAlias "$top.but47" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button $top.but48 \
        -background $vTcl(actual_gui_bg) -borderwidth 6 \
        -font {-family {DejaVu Sans} -size 10 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Delete 
    vTcl:DefineAlias "$top.but48" "Button4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab61 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -image icons8_train_100_png \
        -text Label 
    vTcl:DefineAlias "$top.lab61" "Label7" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab43 \
        -in $top -x 120 -y 20 -width 429 -relwidth 0 -height 81 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra44 \
        -in $top -x 40 -y 120 -width 515 -relwidth 0 -height 255 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but45 \
        -in $top -x 70 -y 390 -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 190 -y 390 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 330 -y 390 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 450 -y 390 -anchor nw -bordermode ignore 
    place $top.lab61 \
        -in $top -x 10 -y 10 -width 99 -relwidth 0 -height 101 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

