#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  May 13, 2020 01:33:19 PM IST  platform: Linux
set vTcl(timestamp) ""


set image_list { \
    icons8_contact_info_96_png ./Documents/Tkinter/img/icons8-contact-info-96.png \
    icons8_info_100_png ./Documents/Tkinter/img/icons8-info-100.png \
    icons8_time_100_png ./Documents/Tkinter/img/icons8-time-100.png \
    icons8_train_100_png ./Documents/Tkinter/img/icons8-train-100.png \
}
   vTcl:create_project_images $image_list   ;# In image.tcl


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m64" -background #18aeef 
    wm focusmodel $top passive
    wm geometry $top 600x450+441+187
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Railways"
    vTcl:DefineAlias "$top" "Railways" vTcl:Toplevel:WidgetProc "" 1
    button $top.but46 \
        -activebackground #000000 -background $vTcl(actual_gui_bg) \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image icons8_contact_info_96_png 
    vTcl:DefineAlias "$top.but46" "Button1" vTcl:WidgetProc "Railways" 1
    button $top.but47 \
        -activebackground #000000 -background $vTcl(actual_gui_bg) \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image icons8_time_100_png -text Button 
    vTcl:DefineAlias "$top.but47" "Button2" vTcl:WidgetProc "Railways" 1
    button $top.but48 \
        -activebackground #000000 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -image icons8_info_100_png -text Button 
    vTcl:DefineAlias "$top.but48" "Button2_1" vTcl:WidgetProc "Railways" 1
    ttk::separator $top.but48.tSe62 \
        -orient vertical 
    vTcl:DefineAlias "$top.but48.tSe62" "TSeparator1" vTcl:WidgetProc "Railways" 1
    button $top.but51 \
        -activebackground #f9f9f9 -background $vTcl(actual_gui_bg) \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -image icons8_train_100_png -text Button 
    vTcl:DefineAlias "$top.but51" "Button2_4" vTcl:WidgetProc "Railways" 1
    label $top.lab57 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Booking Information} 
    vTcl:DefineAlias "$top.lab57" "Label1_8" vTcl:WidgetProc "Railways" 1
    label $top.lab58 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Train timings} 
    vTcl:DefineAlias "$top.lab58" "Label1_9" vTcl:WidgetProc "Railways" 1
    label $top.lab59 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text About 
    vTcl:DefineAlias "$top.lab59" "Label1_10" vTcl:WidgetProc "Railways" 1
    label $top.lab60 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 11 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {New Booking} 
    vTcl:DefineAlias "$top.lab60" "Label1_11" vTcl:WidgetProc "Railways" 1
    label $top.lab63 \
        -background #b7b7b7 \
        -font {-family {Yrsa} -size 22 -weight bold -slant italic -underline 1} \
        -foreground $vTcl(actual_gui_fg) -text {Railway Reservation System} 
    vTcl:DefineAlias "$top.lab63" "Label2" vTcl:WidgetProc "Railways" 1
    set site_3_0 $top.m64
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but46 \
        -in $top -x 10 -y 100 -width 261 -relwidth 0 -height 111 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 340 -y 100 -width 231 -relwidth 0 -height 111 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 340 -y 240 -width 231 -relwidth 0 -height 131 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.but48.tSe62 \
        -in $top.but48 -x 0 -y 0 -height 200 -anchor nw -bordermode inside 
    place $top.but51 \
        -in $top -x 10 -y 250 -width 261 -relwidth 0 -height 121 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 10 -y 210 -width 259 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 340 -y 210 -width 229 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 340 -y 370 -width 229 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 10 -y 370 -width 259 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab63 \
        -in $top -x 0 -y 10 -width 599 -relwidth 0 -height 61 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

